language: scala
scala:
  - 2.11.12
  - 2.12.8
jdk:
  - openjdk11
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
script:
  - sbt ++$TRAVIS_SCALA_VERSION validate
  - if [[ $TRAVIS_SCALA_VERSION == 2.12* ]]; then sbt ++$TRAVIS_SCALA_VERSION validateDocs; fi
after_success:
  - bash <(curl -s https://codecov.io/bash)
